name: preflight_project # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - ${NGINX_PORT}:5175
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
    image: pulom999/preflight_project-frontend:latest
networks:
  preflight_pf-net: # Check by using `docker network ls` command
    external: true
volumes:
  pf-data:
    